server:
  port: 8082

eureka:
  instance:
   hostname: localhost

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: OnlinePlantNurseryapplication_service
          uri: http://localhost:8081/
          predicates:
            - Path=/api/v1/**
       
        - id: Customer_Service
          uri: http://localhost:8086/
          predicates:
            - Path=/api/v2/**
            
        - id: Order_Service
          uri: http://localhost:8084/
          predicates:
            - Path=/api/v3/**
        
        